default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  encoding: unicode
  database: <%= ENV["database_name"] %>
  username: <%= ENV["database_user"] %>
  password: <%= ENV["database_password"] %>

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV["database_name"] %>

production:
  <<: *default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["database_host"] %>
  port: <%= ENV["database_port"] %>
